### ISSUE TITLE
Error api Query

### ISSUE THREAD

**Issue by monrorMe** [OCSAF/freevulnsearch#1]
I get this error "freevulnsearch: Error with API query. API or network possibly not available." every time I run the application.

**Comment by OCSAF** [comment]
Thanks for your message. I'm trying to give you some solutions here.

a)
It can surely happen that the API is not reachable. Unfortunately I have no influence on this. Just try again in an hour. You can check the accessibility with https://cve.circl.lu in your browser. 

b)
Otherwise it is important that you do not use the script together with other optional NSE scripts for high reliability, i.e. only nmap -sV --script freevulnsearch

c)
Of course, general network problems can also trigger the error message. For example the DNS settings. You can check the API in Linux directly with curl.

curl https://cve.circl.lu/api/cve/CVE-2010-3333

For more information visit https://cve-search.org/api/

d) 
You can also install cve-search locally and then specify the local API path (https://github.com/cve-search/cve-search): 
nmap -sV --script freevulnsearch --script-args apipath=URL
However, I have not yet been able to test this.

I hope this helps you and others who get this error message.

**Comment by UBISOFT-1** [comment]
@OCSAF I tried the curl https://cve.circl.lu/api/cve/CVE-2010-3333 and it worked like a charm and still got and error, do you know what else could be the problem.
## Update
```
nmap -sV --script freevulnsearch --script-args apipath=https://cve-search.org/api/ website_here.com
Starting Nmap 7.91 ( https://nmap.org ) at 2020-11-16 21:46 PKT
Nmap scan report for website_here.com (IP-HERE)
Host is up (0.30s latency).
Not shown: 984 closed ports
PORT     STATE    SERVICE     VERSION
21/tcp   open     ftp         Pure-FTPd
22/tcp   open     ssh         OpenSSH 5.3 (protocol 2.0)
|_freevulnsearch: *Error with API query. API or network possibly not available.
25/tcp   open     smtp        Exim smtpd 4.93
|_freevulnsearch: *Error with API query. API or network possibly not available.
26/tcp   open     smtp        Exim smtpd 4.93
|_freevulnsearch: *Error with API query. API or network possibly not available.
53/tcp   open     domain      ISC BIND 9.8.2rc1 (RedHat Enterprise Linux 6)
|_freevulnsearch: *Error with API query. API or network possibly not available.
80/tcp   open     http        Apache httpd
|_http-server-header: Apache
|_http-trane-info: Problem with XML parsing of /evox/about
110/tcp  open     pop3        Dovecot pop3d
143/tcp  open     imap        Dovecot imapd
443/tcp  open     ssl/http    Apache httpd
|_http-server-header: Apache
|_http-trane-info: Problem with XML parsing of /evox/about
465/tcp  open     ssl/smtp    Exim smtpd 4.93
|_freevulnsearch: *Error with API query. API or network possibly not available.
587/tcp  open     smtp        Exim smtpd 4.93
|_freevulnsearch: *Error with API query. API or network possibly not available.
993/tcp  open     ssl/imap    Dovecot imapd
995/tcp  open     ssl/pop3    Dovecot pop3d
2222/tcp open     ssh         OpenSSH 5.3 (protocol 2.0)
|_freevulnsearch: *Error with API query. API or network possibly not available.
2525/tcp filtered ms-v-worlds
3306/tcp open     mysql       MySQL 5.6.41-84.1
|_freevulnsearch: *Error with API query. API or network possibly not available.
Service Info: Host: balaba.hostgator.com; OS: Linux; CPE: cpe:/o:redhat:enterprise_linux:6

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 60.75 seconds
```
# Any Help will be appreciated ;)
